apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: *int32
  minReadySeconds: int32
  selector:
    matchLabels: map[string]string
    matchExpressions: 
    - key: string
      operator: string(In/NotIn/Exists/DoesNotExist)
      values: []string
  template: 
    metadata: metav1.ObjectMeta
    spec: PodSpec
status:
  replicas: int32
  fullyLabeledReplicas: int32
  readyReplicas: int32
  availableReplicas: int32
  observedGeneration: int64
  conditions:
  - type: ReplicaSetConditionType #(string-ReplicaFailure)
    status: ConditionStatus #(string-True/False/Unknown)
    lastTransitionTime: time
    reason: string
    message: string